import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Providers } from "./providers";
import {
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
} from "@nextui-org/navbar";
import { Link } from "@nextui-org/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar
            position="sticky"
            className="bg-white shadow flex justify-center h-16"
          >
            <NavbarContent className="hidden sm:flex gap-4" justify="center">
              <NavbarItem>
                <Link color="foreground" href="/">
                  Home
                </Link>
              </NavbarItem>
              <NavbarItem>
                <Link color="foreground" href="/about">
                  How it works
                </Link>
              </NavbarItem>
            </NavbarContent>
          </Navbar>
          {children}

          <footer className="flex items-center justify-center">
            <p className="text-center">
              © {new Date().getFullYear()} Anonymous Shadchan. All rights
              reserved.
            </p>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
